version: '2'

services:
  application:
    build: .
    image: doc-live
    hostname: 'application'
    working_dir: /home/node/app
    network_mode: bridge
    container_name: application
    volumes:
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
      - $PWD/.bashrc:/home/node/.bashrc
      - $PWD:/home/node/app
    links:
      - "selenium:selenium.dev"

  selenium:
    image: selenium/standalone-chrome
    hostname: 'selenium'
    network_mode: bridge
    container_name: selenium
